/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iTokenSol from "./IToken.sol";
export type { iTokenSol };
export type { IVotingEscrow } from "./IVotingEscrow";
