import type { NextPage } from 'next'
import React, { useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link';
import Script from 'next/script';
import TokenApp from "../../components/TokenApp/index";
import { BasciConnect } from '../../components/ConnectWallet';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';


const FirstPost: NextPage = () => {
    
    return (
        <div className={styles.container}>
            <BasciConnect></BasciConnect>
            <Head>
                <title>fist Post</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>First Post</h1>
            <div>
                <TokenApp></TokenApp>
            </div>
            <div>
                <Card sx={{ minWidth: 275 }}>
                <CardContent>
                <Typography sx={{ fontSize: 14 }} color="text.secondary" gutterBottom>
                    game player
                </Typography>
                <Typography variant="h5" component="div">
                    I am a Game player
                </Typography>
                <Typography variant="body2">
                    Go to the gamer app.
                </Typography>
                </CardContent>
                <CardActions>
                <Button  size="small">
                    <Link href="/posts/second-post" className={styles.card}>
                        learn more 
                    </Link> 
                </Button>
                </CardActions>
                </Card>
            </div>
            <div>
                <Card sx={{ minWidth: 275 }}>
                <CardContent>
                <Typography sx={{ fontSize: 14 }} color="text.secondary" gutterBottom>
                    game devloper
                </Typography>
                <Typography variant="h5" component="div">
                    I am a Game Devloper
                </Typography>
                <Typography variant="body2">
                    Go to the gamerdev app.
                </Typography>
                </CardContent>
                <CardActions>
                <Button  size="small">
                    <Link href="/posts/third-post" className={styles.card}>
                        learn more 
                    </Link> 
                </Button>
                </CardActions>
                </Card>
            </div>
            <div>
                <Card sx={{ minWidth: 275 }}>
                <CardContent>
                <Typography sx={{ fontSize: 14 }} color="text.secondary" gutterBottom>
                    VotingEscrow
                </Typography>
                <Typography variant="h5" component="div">
                    Staking VotingEscrow
                </Typography>
                <Typography variant="body2">
                    Go to the VotingEscrow app.
                </Typography>
                </CardContent>
                <CardActions>
                <Button  size="small">
                    <Link href="/posts/votingEscrow-post" className={styles.card}>
                        learn more 
                    </Link> 
                </Button>
                </CardActions>
                </Card>
            </div>


            <Script
                src="https://connect.facebook.net/en_US/sdk.js" //加载第三方脚本
                strategy="lazyOnload"                           //空闲时加载
                onLoad={() =>
                console.log(`script loaded correctly, window.FB has been populated`)    //用于在脚本完成加载后立即运行任何 JavaScript 代码
                }
            />

            <div className={styles.grid}>
                <Link href="/" className={styles.card}>
                    <h2>Back to home &rarr;</h2>
                </Link>
            </div>
        </div>
    )
}

const YourComponent = () => (
  <Image
    src="/images/profile.jpg" // Route of the image file
    height={144} // Desired size with correct aspect ratio
    width={144} // Desired size with correct aspect ratio
    alt="profileImage"
  />
);

export default FirstPost;
