/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { VotingEscrow } from "./VotingEscrow";
