import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import AppStart from "./api/app";
import { BasciConnect } from '../components/ConnectWallet';
import Box from '@mui/material/Box';
import MuiLink from '@mui/material/Link';
import { AccessAlarm, ThreeDRotation ,GitHubIcon } from '@mui/icons-material';

const Home: NextPage = () => {
  const preventDefault = (event: React.SyntheticEvent) => event.preventDefault();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <BasciConnect></BasciConnect> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://github.com/tangminjie/GameChainDev-interface">GameChainDev-interface!</a>
        </h1>

        <p className={styles.description}>
              contract address :{' '}
          <code className={styles.code}>0xf4d2888d29d722226fafa5d9b24f9164c092421e</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <Link href="/posts/fist-post" className={styles.card}>
            <div>
              <h2>getPost &rarr;</h2>
              <p>get the fist post!</p>
            </div>
          </Link>  

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

      <Box
      sx={{
        typography: 'body1',
        '& > :not(style) + :not(style)': {
          ml: 2,
        },
      }}
      onClick={preventDefault}
    >
      <Link href="#">Link</Link>
      <Link href="#" color="inherit">
       <AccessAlarm />
      </Link>
      <Link href="#" variant="body2">
        <GitHubIcon />
      </Link>
    </Box>
    
    </div>
  )
}

export default Home
